apiVersion: batch/v1
kind: Job
metadata:
  name: all-capitals
spec:
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: sleep
    spec:
      restartPolicy: Never
      containers:
        - name: sleep300
          image: "BUSYBOX"
          command: ["sleep", "300"]
          resources:
            requests:
              cpu: "100m"
              memory: "2000M"