apiVersion: batch/v1
kind: Job
metadata:
  name: secret-example-job
spec:
  completions: 1
  backoffLimit: 1
  podFailurePolicy:
    rules:
    - action: FailJob
      onPodConditions:
      - type: PodHasNetwork
        status: "False"
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: secret-test-container
        image: busybox
        command: [ "/bin/sh", "-c", "cat /etc/secret-volume/*" ]
        volumeMounts: 
          - name: secret-volume
            mountPath: /etc/secret-volume 
            readOnly: true 
      volumes:
      - name: secret-volume
        secret:
          secretName: test-secret 