apiVersion: batch/v1
kind: Job
metadata:
  name: secret-example-job-no-failure-policy
spec:
  completions: 1
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: secret-test-container
        image: busybox
        command: [ "/bin/sh", "-c", "cat /etc/secret-volume/*" ]
        volumeMounts: 
          - name: secret-volume
            mountPath: /etc/secret-volume 
            readOnly: true 
      volumes:
      - name: secret-volume
        secret:
          secretName: test-secret 