apiVersion: batch/v1
kind: Job
metadata:
  name: job-with-no-volume
spec:
  completions: 1
  backoffLimit: 1
  podFailurePolicy:
    rules:
    - action: FailJob
      onPodConditions:
      - type: PodScheduled
        status: "False"
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pvc-container
        image: nginx:latest
        volumeMounts:
        - mountPath: /pv-mount
          name: pv
      volumes:
      - name: pv
        persistentVolumeClaim:
          claimName: example-pvc