apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
spec:
  containers:
   - name: pvc-container
     image: nginx:latest
     volumeMounts:
       - mountPath: /pv-mount
         name: pv
  volumes:
   - name: pv
     persistentVolumeClaim:
       claimName: example-pvc