apiVersion: batch/v1
kind: Job
metadata:
  name: capitals-no-failure
spec:
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      name: capitals-no-failure
    spec:
      restartPolicy: Never
      containers:
        - name: capitals-no-failure
          image: "BUSYBOX"
          command: ["sleep", "300"]
          resources:
            requests:
              cpu: "100m"
              memory: "2000M"