apiVersion: batch/v1
kind: Job
metadata:
  name: donotexist
spec:
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: donotexist
    spec:
      restartPolicy: Never
      containers:
        - name: sleep300
          image: "donotexist"
          command: ["sleep", "300"]
          resources:
            requests:
              cpu: "100m"
              memory: "2000M"